### ISSUE TITLE
MIDI files play at different speeds (in Tone) with different versions of MidiConvert

### ISSUE THREAD

**Issue by rnatter** [pioug/MidiConvert#16]
MidiConvert is TERRIFIC.  Thank you for making it.

I have been using it with Tone.js for some time.
An older version (Jun 2017) parses and plays (with Tone) files as I expect.
Current versions (both Master and Dev) play at greatly increased rate. This happens with my midi files, and also the ones that you include in your /test folder. 
Have included a zip file with a simplified testing environment.
Three html files: only difference is the version of MidiConvert that they use.
Hoping that including simple example will help find the issue. Thanks.

[MidiConvert-testing.zip](https://github.com/pioug/MidiConvert/files/1110683/MidiConvert-testing.zip)

Tested on MacBook Pro OSX10.11.6  Chrome, Safari, Firefox

**Comment by pioug** [comment]
The speed is different because I changed the default PPQ value (from 192 to 128 in the latest version). You can try:

```
CW.midiObj = MidiConvert.parse(reader.result, { PPQ: 192 });
```

And MidiConvert is not from me but https://github.com/Tonejs! You should definitely check the original repo: https://github.com/Tonejs/MidiConvert. I looked through the last commits and they added up lots of useful infos about parsed MIDI files. My fork diverges a lot so it's difficult to merge back unfortunately.
